w3c/png

index.html

Add erratum ["Typographic error in description of tRNS"](https://www.w3.org/2003/11/REC-PNG-20031110-errata).
The 2003 Recommendation [inadvertently had RBG rather than RGB](https://www.w3.org/TR/2003/REC-PNG-20031110/#11tRNS) order for Color type 2.

add erratum "Typographic error in description of tRNS"

---

index.html

Replaces the old Annex A (file extension, media type, mac type) with the current IANA registration template which has all that and more in a standard format.

Add IANA registration template, see #27

---

index.html

Removed old references to png-group@w3.org which is closed.
Updated the "registration authority" wording.
Prefer GitHub issues for registration requests and bug reports
Also point to PNG WG ipr page (for patent disclosures etc)
The Status of this Document will change anyway when we publish First Public Working Draft, but meanwhile the old wording was confusing.

Update contact details

---

index.html

Currently, ReSpec is fetched via HTTP.
If the spec is hosted via HTTPS, the HTTP ReSpec request will be denied
in modern browser settings. This results in ReSpec styling not being
applied.
This commit fetches ReSpec via HTTPS.

Use HTTPS for ReSpec fetch

---

index.html

ReSpec provides a <dfn> tag for definitions. Currently, the definitions
section does not use it.
Additionally, each definition has its section number hard-coded. ReSpec
provides generated section numbers, which enables sections being added
or removed.
This commit uses the <dfn> tag as well as removes hard-coded section
numbers.
Closes #87 and #88.

Use <dfn> and remove hard-coded section numbers

---

index.html

The old References and Bibliography are still there, for checking, but will later be deleted
ISO website is down :) so some missing references at the moment

Convert hardcoded refs to SpecRef

---

index.html

ReSpec is giving an error that the config is missing a group.
This commit adds the correct group to the ReSpec config.
Closes #101

Add group to ReSpec config

---

index.html

The name attribute is not part of the global attributes:
https://w3c.github.io/html-reference/global-attributes.html
This commit uses the id attribute instead of the name attribute.
Closes #103

Use id attribute instead of name

---

index.html

Tables were using the old fragment style <a name="frag_name"></a>.
ReSpec correctly errored on these.
ReSpec has a special way to handle figures. But it doesn't yet have a
special way to handle tables. There is discussion about this here:
https://github.com/w3c/respec/issues/4004
This commit will leave the tables in place for now (not using any
special ReSpec handling) but corrects the fragments. It also adds a
comment to preserve fragments. This fixes several ReSpec errors.
Closes #99

Fix broken table fragments

---

index.html

There was a missing comma in the ReSpec config which was causing a JS
error. Additionally, the indentation of a few elements was off.
This commit fixes those things.

Fix ReSpec config

---

index.html

It helps if I actually [read the documentation](https://respec.org/docs/#definitions-and-linking) on ReSpec linking to defined terms. I was using `[[defined term]]` but it should be `[=defined term=]`
These are just fixing  the recently-introduced APNG-related definitions.
The other unused definitions which ReSpec complains about will need work to keep the old and the new IDs (perhaps like this:
```html
<dfn>
<a id="3oldId"/>
<dt>Term with no ID</dt>
</dfn>
```

Use correct ReSpec syntax for linking to terms.

---

index.html

Currently, two links to a figure are broken. ReSpec is erroring on this.
This commit fixes those broken links.

Fix linking to figure

---

index.html

The previous PNG spec used "<a name=" for fragments. This was changed to
"<a id=" to become HTML-conformant.
However, ReSpec wants all anchor tags to link to a destination rather
than be an empty tag.
This commit removes empty anchor tags by placing the ids on more correct
tags.
Note, ReSpec requires `<section id="conformance">` which prevents using
the old id. Any tag after this section will come below ReSpec's
generated conformance introduction. So an empty `<div>` is created above
the section to preserve the old id/fragment.

Stop using "<a id=" for fragments.

---

index.html

In a previous commit, the PLTE chunk's fragment was incorrectly changed
to #plte-palette. It was changed back, but links to it were left broken.
This commit fixes those broken links.

Fix linking to PLTE chunk

---

index.html

~~Remove remaining "this International Standard", replacing with "this specification".~~
Remove old, confusingly named "Relationship to W3C PNG" section, which was about first to second edition changes and [still exists in PNG Second Edition](https://www.w3.org/TR/2003/REC-PNG-20031110/index.html#F-Relationship) and replace with modern Changes section.
The previous editor and author names, which were also in that old section, are already in the header of the document.

Remove "Relationship to W3C PNG", add up to date changes section

---

index.html

This is a duplicate of Chris Lilley's iCCN pull request https://github.com/w3c/PNG-spec/pull/117 .
This pull request squashes several commits down and addresses some of the code review comments.
It does not yet address iCCM concerns (or adding the #iccn-embedded-icc-profile fragment). Once we confirm iCCM is an option for us, I'll address those.

Add iccn chunk2

---

index.html

There is an opening <p> tag followed by a closing </a> tag. These are
mismatched.
This commit replaces the closing </a> tag with the </p> tag it was
supposed to be.

Fix mismatched tag

---

index.html

This patch is the first in a series which will use ReSpec's formatting
for internal links.
It is broken into pieces to make review manageable.
ReSpec will format non-definition internal links with the auto-generated
section number. Definition internal links do not receive any special
styling. But using them is forward compatible if ReSpec later decides to
apply formatting.
This is part of #122 and #123.

Use ReSpec for internal links (1 of N)

---

index.html

Currently, several links on the spec anchor to
"#iccn-embedded-icc-profile". But there is no matching anchor by that
name.
This commit replaces those broken links with the ReSpec generated link,
which also includes the generated section number.

Fix iCCN fragment links

---

index.html

This patch is the second in a series which will use ReSpec's formatting
for internal links.
It is broken into pieces to make review manageable.
This continues the work from #124 and is part of #122 and #123.

Use ReSpec for internal links (2 of N)

---

index.html

Per my action from the last call.

Remove mention of ICC.2 (iccMAX) from iCCP chunk definition

---

index.html

- Fix up all normative references marked as _Reference not found._
- Update obsolete references to current versions
- Fix up existing informative references
- Check the old hard-coded Normative Refs section, make sure any remaining ones were actually unused, then delete it

Fix references to use ReSpec and SpecRef

---

index.html

Previously, we considered the iCCP chunk should be for ICC v2 profiles
only. This is what prior editions of the spec made explicit. So a new
chunk (iCCN) would allow ICC v4 profiles.
However, it was decided that the existing iCCP chunk can safely contain
ICC v4 profiles and a new chunk is not needed.
This commit moves the comments about the iCCN chunk into the iCCP chunk,
allowing the iCCP chunk to handle ICC v4 profiles.
Closes #95

Merge iCCN chunk into iCCP chunk

---

index.html

Previously, in #124 internal links were updated to use ReSpec
formatting. However, it used MD style instead of HTML style.
This commit updates that change to use HTML style instead.
This is part of #122 and #123.

Use HTML style internal links (1 of N)

---

index.html

Trim unused references
Trim non-normative references to out of print books (including my own :) )
Remove hard-coded bibliography section (replaced by ReSpec Informative References)
See https://github.com/w3c/PNG-spec/issues/82

Use Informative References, not hard-coded Bibliography

---

index.html

The missing comma makes the script syntactically invalid and prevents spec generation by ReSpec.
Missing comma was introduced by recent local biblio changes.

Add missing comma in ReSpec config

---

index.html

ReSpec was recently updated to support table tracking the same way it
supports figures. This landed in https://github.com/w3c/respec/pull/4200
ReSpec already supported class="simple" on tables to gain styling.
This commit adds both of these to all tables in the PNG spec.
This also means adding captions and headings to tables which were
missing it.
Closes #138

Update table styling

---

index.html

A closing `</span>` was actually `</`

Correct malformed markup, fix #145

---

index.html

The cICP chunk is missing a closing </section> tag.
As a result, the table of contents and section numbers are off.
For example, what would be section 12, PNG Encoders is instead 11.4.
This is under section 11, Chunk specifications.
Clearly, encoding is not part of the chunk spec.
This commit restores the missing </section> tag.

Add missing closing </section> tag

---

index.html

The reference incorrectly was `[[??Kasson]]`, should be `[[?Kasson]]`

Fix informative ref to Kasson

---

index.html

Normative ref to RFC1952 for CRC algorithm. Sample code is informative, appendix is not.

Norm ref RFC1952 for CRC algorithm.  Fix #12

---

index.html

No longer recommend adding redundant `gAMA` and `cHRM` when better methods like CICP, ICC, or sRGB are used: the description for these chunks says to ignore it anyway. These are now legacy chunks.

Don't recommend redundant gAMA, fix #151

---

index.html

Recommend using UTF-8 `iTXt` rather than Latin-1 `tEXt` for new, textual information.

Recommend iTXt, fix #144

---

figures/lattice-diagram-apng-static-first-with-plte.svg
figures/lattice-diagram-apng-static-first-without-plte.svg
figures/lattice-diagram-apng-static-notfirst-with-plte.svg
figures/lattice-diagram-apng-static-notfirst-without-plte.svg
figures/lattice-diagram-with-plte.svg
index.html

Adds four diagrams:
-  APNG with PLTE, first frame is IDAT
-  APNG with PLTE, first frame is not IDAT
-  APNG with no PLTE, first frame is IDAT
-   APNG with no PLTE, first frame is not IDAT
Fixes one other diagram which still showed a bounding box rectangle used during editing
Adds these diagrams to the spec.
The figure elements have sensible ids. The object elements have ids, which are at least unique, but I would also be fine with dropping the object ids.

Add missing chunk ordering diagrams (APNG), fix #143

---

index.html

Add descriptions of the type of information contained in `cICP` and `eXIf` chunks

Add `cICP` and `eXIf` to ancillary info table, fix #168

---

index.html

Defines opaque black as one common error recovery method.
Decoders have varied, so encoders must not rely on this presentation.

Oor palette index, fix #96

---

index.html

I had to use best judgement in some cases.
There seem to have been a conscious decision to differentiate between the image type (`Greyscale`) and the corresponding value of the `colour type` field (0). Sometimes both are present together, e.g. Table 8. I suggest we keep this unchanged.

Clean-up colour type definition

---

index.html

The many filtering sections are not easy to understand. This commit moves filtering paragraphs and rewords things slightly. The result is a more clear introduction.
This commit also adds a link from a specific filtering section back to the introductory section.
This contributes to #11

Reword filtering introduction

---

index.html

There are several CSS classes which were added and removed through the various PNG spec drafts. Several tags references classes which have been removed. These tags provide no value.
This commit removes unused CSS classes.
Note: This commit leaves '<span class="chunk">' in place. We deemed those may still be useful. A separate commit will consider changing them to '<a class="chunk">'.
Contributes to #135

Remove unused classes

---

index.html

ReSpec requires all sections to start with a h2-h6 tag. This includes introductory sections.
Previously, introductory sections did not include a header because the text "Introduction" was superfluous. However, fixing ReSpec errors is more important.
This commit adds <h3>Introduction</h3> to each introductory section, fixing some ReSpec errors and warnings.
This contributes to #86

Add header to introductory sections

---

index.html

In prior editions of the spec, fragments often had their section number hard-coded into them. For example, #11iTXt.
For future fragments, we should not hard-code section numbers like this. They might change.
This commit changes new-to-third-edition fragments to not hard-code section numbers.

Don't hard-code section numbers in new fragments.

---

index.html

The 'chunk' class is unused. However, keeping it around could be useful for later.
Rather than keep it as a span, it should be an anchor link.
This commit replaces '<span class="chunk">' with anchor links.
Note: '<span class="chunk">' is left intact when defining the chunk itself. For example, the pHYs chunk doesn't link to itself.

Replace '<span class="chunk">' with links.

---

index.html

There are a few headers which include links in them. The default table header background is dark blue. And the default section link is brown. This brown text on top of dark blue background is difficult to read.
Further, headings shouldn't contain links, anyway.
This commit removes links from within headers.
Closes #187

Remove links from headers

---

index.html

There is a typo with <td"> that was causing problems. There is also code that was meant to be deleted ('<span class="' at the end of a line) which was left in place.
This commit fixes both of those mistakes.

Fix typo and leftover code

---

index.html

There are a handful of clear HTML errors that the W3C HTML validator finds. For example, closing tags which are doubled up.
This commit fixes several of these HTML errors.

Fix HTML validator errors

---

index.html

There is a link with "`</a`" instead of "`</a>`". This broken closing tag caused text behind it to be included in the link.
This commit fixes the closing tag.
Closes #202

Fix unterminated link

---

index.html

In commit 0326839ddb0 I updated the fdAT chunk fragment identifier to not use the old style which included section numbers. However, I missed several links which reference that old fragment identifier.
This commit fixes the broken links.

Fix fdAT links

---

index.html

Previously, almost all chunk references were annotated with `<span class="chunk">`. These were updated to links, `<a class="chunk" href="#dest">`. However, that leaves room for the posibility that some chunk references were not previously annotated and did not gain links.
This commit updates all previously unannotated chunk references to contain links.
Closes #189

Add links to chunk references

---

index.html

The W3C HTML Validator strongly recommends against using self-closing tags. These tags are void elements in HTML 5. This means they cannot contain anything and thus a separate closing tag is disallowed.
This commit replaces self-closing tags ("/>" style) with the recommended opening tag only for void elements.

Don't use self-closing tags

---

index.html

There is an <a> element that doesn't link anyway. It is given an id to be a link destination. ReSpec does not understand the intent of this empty, no-destination anchor element. ReSpec errors on this strange situation.
This commit removes the erroring <a> tag and maintains the id on a more appropriate tag.

Fix ReSpec error

---

index.html

• Changed to "CICP image format signaling metadata"
• Changed generic descriptions of "colour space" to Colour Space, Transfer Function and Matrix Coefficients. (more informative of function)
• Added "Wide Colour Gamut" to description of CICP signaling capabilities.

Subtle changes to nomenclature for CICP metadata

---

index.html

Remove the definition for PNG two-byte integers (#221, #216)

---

index.html

Remove the definition for PNG four-byte signed integer

---

index.html

The [First Public Working Draft](https://www.w3.org/TR/2022/WD-png-3-20221025/) is published today, so this PR:
- Updates shortname to png-3, like the FPWD
- Removes publication date, so it is always the date of last edit
- Updates previous publication date and status
-  Sets status back to Editors Draft

Updates after FPWD

---

tidy.cfg

The vertical-space config option was not grouped with its other options. This commit puts it in its "Pretty print options" group.

Cleanup tidy config

---

.github/workflows/formatting-checker.yaml

Currently, the GitHub workflow (which runs on every pull request) will report errors if the existing files contain errors. This is unfortunate because people who create new pull requests will see an error when they did not cause it.
This commit will instead only error if the pull request introduces a new error.

Only error on new GitHub workflow issues

---

index.html

Corrects both paragraphs per @aphillips suggestions. Adds links to I18n glossary.
ReSpec complains about these being normative.

Prefer iTXt

---

index.html

This commit adds the mASt chunk, which provides mastering metadata as specified by SMPTE ST 2086.
Contributes to #236.

Add mASt chunk

---

index.html

- Convert 4-byte decimal chunk signatures to hex. (Previous decimal values retained in comments for verification)
- Consistent introductory text. Most used
```html
<p>The four-byte chunk type field contains the hexadecimal values</p>
```
but a few used this style
```html
<p>The four decimal values below correspond to the four-byte gAMA chunk type field:</p>
```
Now they all use the shorter, clearer text.
- PNG signature had both decimal and hex, now has hex only.
- A few other occurrences of decimal values (like specifying ranges of control characters in text) also converted to hex
These are all accompanied by text stating _explicitly_ that the values are hexadecimal, so I didn't use noisy `0x4C` just `4C`

decimal to hex

---

index.html

The id was incorrect so Chris Seeger was being interpreted as Jen Williams.

Use correct id number for Chris Seeger

---

index.html

ITU BT.2408-6 suggests 203 cd/m^2, not 200.
This commit updates our example to use 203 cd/m^2.

Use 203 cd/m^2 instead of 200

---

index.html

Currently, the Scope section goes into details beyond the scope. These details are described elsewhere. They don't really belong (nor are they needed) in the Scope section.
This commit follows the suggestion from @palemieux to remove this extra information from the Scope section.
Closes #269

Simplify Scope section

---

index.html

* Avoiding repeating definitions that are already in the body of the REC
* Bring terms and definition section to ISO editorial standards
* Merge abbreviation and definition sections
* Clean-up abbreviations
Closes #156

Refactor terms and definitions sections

---

index.html

Previously, a reference was named with "ITU_T Series H...". But that should have been "ITU-T Series H...".
This commit corrects the hyphenation. Additionally, it links to the reference.

Correct hyphenation and link to reference

---

index.html

There is wording of "cd/m2", which doesn't have the 2 raised like it should be. Additionally, the wording says "or nits" which may be confusing.
This commit changes that wording to be more accurate and hopefully also more clear.

Update units representation

---

index.html

There are instances of `MDCV` which should be `mDCv` and `CICP` which should be `cICP` when referring to those chunks.
This commit corrects the chunk title casing.

Correct chunk casing

---

index.html

Previously, the description for MaxFALL sounded a bit like it involved only a single frame. @svgeesus suggested wording that might read in a way that better indicates MaxFALL.
This commit uses @svgeesus's suggested wording.

Clarify MaxFALL wording

---

index.html

Currently, there is a typo: "othen". It is supposed to be "other".
This commit corrects that typo.
Closes #296

Correct typo

---

index.html

Adds the three proposed paragraphs from https://github.com/w3c/PNG-spec/issues/282#issuecomment-1511449129 .
Does not close the issue, we might want to add encoder advice and we are also waiting for the original commenter to get back about our questions.

Add known privacy issues, helps with #282

---

index.html

Moves the definition of frame, which was introduced as part of `cLLi`, to the definitions section. This covers all three cases:
1. Static PNG (one frame)
2. Animated PNG, static image is first frame (all images in the PNG are frames)
3. Animated PNG, static image is not first frame (static image not counted as a frame)
References that definition from `cLLi`.

Define frame, fix #286

---

figures/lattice-diagram-apng-static-first-with-plte.svg
figures/lattice-diagram-apng-static-first-without-plte.svg
figures/lattice-diagram-apng-static-notfirst-with-plte.svg
figures/lattice-diagram-apng-static-notfirst-without-plte.svg
figures/lattice-diagram-with-plte.svg
figures/lattice-diagram-without-plte.svg

The lattice diagrams still had the old `mLUm` chunk name; changed to `cLLi`.

Change mLUm to cLLi

---

index.html

This PR only deals with UTF-8 encode and decode, for `iTXt`. It partially resolves #273
(We haven't yet got data to make a real Latin-1 vs 1252 decision for `tEXt` and `zTXt`.)

Follow Encoding standard on UTF-8 encode and decode

---

index.html

Fixes https://github.com/w3c/PNG-spec/issues/315

Remove redundant note, fix #315

---

index.html

This commit adds a note that unused trailing bytes may exist in the final IDAT chunk, explaining preferable handling.
Closes #158

Add note on unused trailing IDAT bytes

---

index.html

- fixed broken reference links
- fixed broken HTML markup
- reference IDs can't contain spaces
- explicit publication date (remove, once published)
- change status from ED to WD (revert, once published)
- update date of previous publication
- some linkfixes, http to https etc
- corrected duplicate IDs on examples

Changes required to pass W3C publication checker

---

index.html

Added the wording [I proposed 2 weeks ago](https://github.com/w3c/PNG-spec/issues/96#issuecomment-1630849503) which is also the behavior of all browsers.

Mandate universal browser behavior, fix #96

---

index.html

- Added definitions of HDR, SDR, PQ, HLG and stop
- Updated text about narrow range image formats
- Updated removing TV specific terminology
- Fixed ITU-T Supplement 19 link
- Added note about calculation of MaxFALL and MaxCLL for animated PNG
Once we're happy with the text, still need to:
- Link to definitions from main text

Addressing #341 #342 and #343 

---

index.html

This is a follow up to @simontWork's PR https://github.com/w3c/PNG-spec/pull/345
Changes: 
- The SDR and HDR definitions were swapped
- Added links to HDR related terms throughout the spec
- Moved a "NB" in the transfer function definition to a Note
- Fixed all ReSpec warnings
(My editor is configured to trim trailing spaces, so there are a few lines with whitespace only changes. I hope this is OK.)

Fix definitions and add links to defined terms

---

index.html

We were missing changes since the [20 July 2023 WD](https://www.w3.org/TR/2023/WD-png-3-20230720/), and the CR transition needs a link to the latest changes

Added changes since WD of 20 July 2023

---

index.html

As [discussed on the issue](https://github.com/w3c/PNG-spec/issues/337#issuecomment-1654365393) and also [on the earlier PR](https://github.com/w3c/PNG-spec/pull/339/files#r1289679856) this follow-on PR fixes up some [minor issues](https://github.com/w3c/PNG-spec/pull/339#issuecomment-1691984267) and adds a reference to "On the Calculation and Usage of HDR Static Content Metadata".
Previous inline references have been updated to Informative References.
A couple of minor markup issues corrected and a broken reference to BT.2100 fixed

MaxCLL and MaxFALL fixup

---

index.html

Explicitly remind that concatenated data from IDAT and fdAT may include zero-length chunks

Zero-length chunk data, fix #356

---

index.html

"Currently only RGB is the supported color model in PNG" was awkward phrasing.

Improve wording in cICP section

---

index.html

This PR makes a few changes to the mDCV chunk section of the spec.
Examples 9 through 12 are currently very specific to the TV industry and uses TV specific terminology. In essence, these examples hint at a TV broadcast specific profile of the use of the PNG format, rather than being useful information for PNG encoder or decoder implementers.  As such, these examples would be better placed in a document that describes how to use PNG, rather than in the PNG spec itself, which shouldn't imply any specific workflow.
So this PR replaces those examples with equivalent sRGB SDR examples, a format which is far more commonly used. It also address some of the terminology issues in #346.

mDCV chunk spec

---

index.html

No longer claims that `fdAT` can be zero length, but clarify the `frame_data` can be zero length.
Generally tighten wording around chunk concatenation, explicitly mention "in ascending sequence number order".
Link back to the section in Concepts on sequence numbers.

Clarify sequence numbers and zero-length fdAT, would fix #379

---

index.html

This addresses some confusion we had while building the conformance files for cICp and removes the sRGB example that was unnecessary (it duplicates functions already existing in PNG)

Added unsigned integer examples for cICp Chunk

---

index.html

Added additional description for typical behavior. "RGB images are typically full-range"

Prefixed explanation of full-range PNG

---

index.html

Per my comment in https://github.com/w3c/PNG-spec/pull/383

Remove decimal cICP chunk examples

---

index.html

From the note, link to the actual normative requirement for 16-bit compare

Link to normative requirement, fix #361

---

index.html

- Fixed dangling sentence on use of sub-black and super-white in video formats
- Changed wording on Tone-mapping to indicate it was permissive (original sentence was neither permissive for obligatory)
- Added note on full-range BT.709 images
- Added note on using mDCV to flag non-standard viewing conditions
- Changed sentence on tone-mapping for a target display - the mDCV and cLLI don't target specific displays, they may (or may not) augment tone-mapping for a range of displays 
- Removed sentence on this method of tone-mapping being subjecive.  They are all subjective with optimisations for hue preservatin, highlight detail, saturation etc.
- Added note on display metadata being most important for absolute luminance formats.

Update as per meeting minutes

---

index.html
tools.md

1. Updated HDR10 paragraph as HDR10 requires both mDCV and cLLI and this was not reflected in the text.
2. Swapped sentence order to ensure HDR and SDR lists were aligned correctly.

Correction for HDR10

---

index.html

Better than the original definition (which was factually incorrect) while still pointing out the most important factor (it applies to visible wavelengths only and is weighted for human photopic vision; yellow green will have higher luminance that reds or blue-violets).
Trying to strike a balance between being correct, and being overwhelming with an over-long definition.

better but still short luminance definition, fixes #406

---

index.html

and use consistent section numbers in section links.
There were actually less of these than I thought. In general we use section links correctly. There were a couple using the wrong style, so there was no section number; I fixed them
There was only one where a chunk was linked twice, with both syntaxes.
We also have "see Figure xxx" and I regularized the case on a couple which said "See figure xxx".

Clean up some "two links, same place", fix  #194

---

index.html

This PR rephrases the cLLI chunk description. The current text has:
> If present, the cLLi chunk identifies two characteristics of HDR content:
which seems intended to be followed directly by the description of MaxFALL and MaxCLL. This PR reorders the paragraphs (with some slight rewording) to do that.

Rephrase cLLi chunk description

---

index.html

Because we have two passing implementations, Blink and WebKit

`eXIf` no longer at-risk

---

index.html

The HDR10 reference was failing because the bibliography entry called it HDR 10 (with a space) so it didn't match. Plus, spaces are not allowed there. So I fixed it by using HDR10.

Space not allowed in bibref

---

index.html

The list of changes since the [21 Sept 2023 CR Snapshot](https://www.w3.org/TR/2023/CR-png-3-20230921/) was missing, so I added it from the [GitHub commit history](https://github.com/w3c/PNG-spec/commits/main/index.html?before=0ef99d495a6e9c25a404de2c53b5a43b8d7cd26d+35).
I noticed that some changes before that were missing too, so added those as well.
I omitted changes that we made, and then backed out without publishing to /TR in between (such as putting `eXIf` at-risk and then no longer at-risk)

Updated list of changes, to 20 Feb 2024

---

index.html

Suggested fix for
- https://github.com/w3c/PNG-spec/issues/423
In this PR I also:
- added explicit IDs for all four cICP examples, because otherwise the auto-generated self-links are fragile "#example3" which will go to the wrong place if an earlier example gets added
- corrected two nearby instances of `cICp` to `cICP`

Added explicit mention of Display P3 signalling, plus example. Fix #423

---

index.html

Spotted and fixed (missing "#") broken link

Fix broken respec link in tRNS

---

index.html

This was causing ReSpec errors: "ReSpec doesn't support expanding this kind of reference". This change also adds links in other places where those terms are used.

Fix links to Alpha compaction and Alpha separation sections

---

index.html

Recommend using extended transfer functions to handle negative values

---

tools.md

Understands (does not discard) `cICP`

Added OxiPNG to tools list

---

index.html

Resolved by making the non-free spec informative. EBU r103 is free, remains normative, and explains it well.

Mark RP 2077 as Informative, fix #433

---

index.html

Sorry, I should have suggested this as part of https://github.com/w3c/PNG-spec/pull/439. As well as trying to clarify the wording, this also fixes the link to the sRGB chunk section.

Reword description of color chunk priorities to be more precise

---

index.html

This needs to be up to date, so the implementation report can demonstrate that each substantive change is tested.

Update cumulative list of changes from second to third edition

---

index.html

Used suggested reference to color chunk precedence from
https://github.com/w3c/PNG-spec/issues/443#issue-2217267722
Except for `cICP`, the wording was modified because if is the highest precedence.

Harmonise references to color chunk precedence, fix #443

---

index.html

In Second Edition, all fields were allowed to have private values when the value was 128 or greater.
This shouldn't have been *all* fields, since some rely on values greater than 128 such as height and width.
Third Edition explicitly listed fields which could be private. Currently, it lists 3 of the 5 IHDR fields (ignoring width and height). However, those other two fields would be useful as private, too. Those fields are bit depth and colour type.
This commit adds those two fields to the list of explicitly allowed private fields.
Closes #446

Add private bit depth and colour type fields

---

index.html

This is not quite ready to land. I went through all commits and added them to the changes section. However, several of the commits are adding the Implementation Report. One updates the PNG tools document. As those are separate documents, I don't think they should be listed in changes to the spec itself, right?
Also, this assumes https://github.com/w3c/PNG-spec/pull/387 and https://github.com/w3c/PNG-spec/pull/451 land. They haven't yet.
Once I know if separate document changes should be listed, I'll update this pull request to be in a ready-to-land state.

Update changes section

---

Implementation_Report_3e/index.html

The implementation report used to have special pleading that some tests in Safari would pass, if only wpt was running macOS 14 instead of 13.6. This is no longer needed because WPT is now running macOS 14.5.
Also updated browser versions to current WPT ones.
Also fixed an error (one failing test was incorrectly shown in the table as the preceding test, my bad)

WPT now uses  macOS 14.5 so live tests pass

---

Third_Edition_Explainer.md

Third byte always has the value of `0`, not `1`, according to https://w3c.github.io/PNG-spec/#cICP-chunk

cICP->Matrix Coefficients is always 0, not 1

---

figures/indexed-colour-image.svg
figures/possible-pixel-types.svg
index.html

An earlier pull request changed human-visible colour to color in index.html {preserving second edition links that use colour)
https://github.com/w3c/PNG-spec/pull/411/files
However:
- the svg images still used the colour spelling
- a couple more usages of colour have crept back since
Now fixed by this PR.
Also, the change log about private color type values could have been read as a new feature; I reworded it to be a clarification.

Colour in images, fix #374

---

index.html

Changes for publication as a Candidate Recommendation Draft.
Notice that we [did **not** get permission](https://github.com/w3c/transitions/issues/636#issuecomment-2223346229) for a Candidate Recommendation Snapshot, and thus need to go through Horizontal Review again, _plus_ document review from [external organizations as specified in the charter](https://www.w3.org/Graphics/PNG/png-2023.html#coordination). But to restart horizontal review we first need a CRD, which will hopefully be published this Thursday.
There was also concern we didn't get review for substantive [changes since FPWD](https://www.w3.org/TR/png-3/#changes-20230720). The sole substantive change was:
- Mandated current browser handling of out-of-range palette indices
which we [have a test for]() as [documented in the …

2024 07 18 crd

---

Implementation_Report_3e/index.html

Chris Seeger confirmed that Avid Media Composer added CICP support as mentioned here:
https://lists.w3.org/Archives/Public/public-png/2024Aug/0002.html
This commit adds Avid Media Composer to the cICP section of the Implementation Report.

Add Avid Media Composer to Implementation Report

---

Implementation_Report_3e/index.html

[Servo](https://servo.org/), a web browser engine written in Rust, is an independent implementation so is important despite being less mature than the main browser engines. Servo results are not displayed by default on WPT.fyi but can be enabled.
Servo implements PNG (but not APNG and not `cICP`) however I noticed that it does correctly implement the Third Edition handling of invalid palette indexes and the handling of unknown invalid ancillary chunks:
- [ancillary chunks](https://wpt.fyi/results/png/errors?label=master&product=chrome%5Bexperimental%5D&product=edge%5Bexperimental%5D&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&product=servo&aligned)
- [palette indexes](https://wpt.fyi/results/png/trns-chunk.html?label=master&product=chrome%5Bexperimental%5D&product=ed …

[ImpReport] add Servo results

---

index.html

Two new editors were added to the authors section. I believe the authors section is intended for the original authors of 1.0. When someone updates the spec, I believe they should be listed as an editor.
This commit moves two people from the authors section to the editors section to reflect this.

Move editors to editor section

---

index.html

In commit 1d54517, some JSON objects were moved around. The missing trailing comma typical to JSON was not added back for the non-trailing case. This caused a parsing error.
This commit corrects the commas from that previous commit.
It also removes a trailing comma that was apparently previously allowed. This matches the style of the rest of the JSON. Although, perhaps we should opt into trailing commas to make life easier.

Correct JSON commas

---

index.html

With Chris Needham and Simon Thompson added to the editors list, ReSpec was warning that editors were missing w3cids.
This commit adds their w3cids.

Add w3cids to new editors

---

index.html

This was to fix the reference to cd/m2 in the divisor column when it should be in the description column.  A previous branch attempted to fix this but for some reason both moves (Max and min) didn't make it into the final pull request.  This should address the other column's move.

fixed reference to cd/m2 in wrong column in MDCV chunk

---

index.html

The cLLI chunk depends on image data. As a result, it is not safe to copy if that pixel data changes.
This commit renames the cLLi chunk to cLLI to reflect the unsafe-to-copy behavior.

Rename cLLi to cLLI

---

index.html

The mDCV chunk depends on image data. As a result, it is not safe to copy if that pixel data changes.
This commit renames the mDCv chunk to mDCV to reflect the unsafe-to-copy behavior.

Rename mDCv to mDCV

---

index.html

The `acTL` chunk description, and the lattice diagrams, show that `acTL` is only required to be before `IDAT`, not before `PLTE` as well. This PR makes the chunk ordering table consistent with the chunk description and lattice diagrams.

Consistently require only that acTL is before IDAT, not PLTE #467

---

figures/lattice-diagram-apng-static-first-with-plte.svg
figures/lattice-diagram-apng-static-first-without-plte.svg
figures/lattice-diagram-apng-static-notfirst-with-plte.svg
figures/lattice-diagram-apng-static-notfirst-without-plte.svg
figures/lattice-diagram-with-plte.svg
figures/lattice-diagram-without-plte.svg

The earlier find and replace had missed the figures because they are separate files.
Also corrected a typo (mDVc) to mDCV

Update SVG figures for mDCV, cLLI

---

Implementation_Report_3e/index.html

[Ladybird browser](https://github.com/LadybirdBrowser/ladybird?tab=readme-ov-file) supports:
- APNG
- CICP (as of a couple of days ago)
- Priority of color space info
- EXIF orientation in PNG
- Invalid `tRNS` palette index handling
- Handling unknown, invalid ancillary chunks
For those tests where WPT reports results, I have added them.
Building the browser (there are no precompiled binaries) requires a MacOS or Linux/Qt system which I don't have. So there are no results for manual tests in this PR.
I also added pngcheck as supporting PNG, `cICP`, `mDCV` and `cLLI`.

Implementation report, feb 2025 update

---

Implementation_Report_3e/index.html
tools.md

The cicp_inserter project has been renamed to png_cicp_editor to reflect the fact that it can now do more than insert.
This commit updates references to the name.

Rename cicp_inserter to png_cicp_editor

---

Implementation_Report_3e/index.html

Firefox was the only browser to fail on the Third Edition `trns` test; as of today Firefox 139 nightly passes.
In this PR I also updated all browser versions to the ones currently used on WPT.

Firefox trns pass
