- index.html
> Replace " ." with "." for #13

- index.html
Adds ICC.1 and ICC.2 to normative references
> Update ICC normative refs, for #22

- index.html
Hi Chris(s), Pierre-Anthony, Leonard, Lars,
Here is my first attempt at the specification adding cICP.  I look forward to hearing your suggestions for improvements and conformance to W3 requirements.
> 1st Attempt - cICP Chunk For PNG Specification

- index.html
More descriptive information added.
> Cleaned up definition for cICP Chunk

- index.html
added language around assumed matrix coefficient value.
> Fine-tuned language defining cICP Chunk

- index.html
A few edits for clarity ad consistency, and to correct copy-paste error in the examples
> cICP tweaks

- index.html
Added Matrix Coefficients based on comments; added descriptions and examples.
> Added Matrix Coefficients

- extensions/Overview.bs
- extensions/Overview.html
- index.html
> Move XMP to core spec

- index.html
From http://ftp-osl.osuosl.org/pub/libpng/documents/pngext-1.5.0.html#C.eXIf
> Add eXIf from old extensions spec

- index.html
Remove requirements for a Registration Authority
Closes #49
> Clarify guidance on adding chunks

- index.html
@svgeesus orginally wrote this code. It is being moved out to a separate
commit.
This commit adds an eXIf entry in the chunk ordering rules table.
> Add table entry for eXIf placement

- index.html
@svgeesus originally wrote this code. It is being moved out to a
separate commit.
This commit adds a cICP entry in the chunk ordering rules table.
> Add table entry for cICP placement

- index.html
ReSpec has a special method to create an introductory section.
This commit changes APNG's "General" section to be introductory.
> Make APNG general section introductory

- index.html
> Remove hard-coded heading numbers

- index.html
> Conform cICP chunk to Rec. ITU-T h.273

- index.html
Small cleanup in the local references
> Cleanup biblio refs

- index.html
> Fix internal and definition links

- index.html
> Fix broken fragments

- index.html
"Lossy compression" is not used
> Delete lossy compression definition

- index.html
> Delete LUT abbreviation

- index.html
Add empty section with link to tagged privacy issues
> Add privacy considerations, fix #214

- index.html
> Added improved description of narrow range

- index.html
Added definition of transfer function and gamma value
> Clean-up gamma definition

- index.html
Another incorrect description of reference white was corrected.
> Additional fixes to description of Narrow Range

- extensions/Overview.bs
- extensions/Overview.html
> Update links in extensions document

- figures/chunk-bits.svg
- figures/depth-original.svg
- figures/depth-scale.svg
- index.html
> fix ascii-art figures, fix #84

- .github/workflows/formatting-checker.yaml
This commit runs HTML Tidy on pull request to notify users of formatting mistakes.
It does not block that pull request from landing. We do not want to add barriers at the moment. Rather, a simple notification is given. It can be ignored or addressed at a later time.
> Add formatting notification

- index.html
Incorporate changes from IANA review of the image/apng registration request.
This makes our appendix identical to the [accepted registration](https://www.iana.org/assignments/media-types/image/apng).
> Update image/apng registration

- index.html
> Clarify the description of the language tag field of the iTXt chunk

- index.html
Downloaded each ITU spec to check the links, and copied the titles from them. Also added dates.
> Correct ITU titles, fix #249

- index.html
I hope I got this right.  It's a start.
> Added new text explaining mAst and new mLum check (MaxCLL/MaxFall)

- index.html
Fixed descriptions of MaxCLL and MaxFall
> Closes: Example 14 talks about minimum luminance in the max luminance section #263

- index.html
See https://github.com/w3c/PNG-spec/pull/266 for discussion.
> Remove empty 'Archive sites' section

- index.html
> Clean-up types of PNG image

- index.html
> Require Matrix Coefficients to be 0, fix #302

- index.html
> Not a separate spec, fix #317

- index.html
Use [suggested wording](https://github.com/w3c/PNG-spec/pull/325#issuecomment-1640935900)
> Adopt @ProgramMax suggested wording, #317

- index.html
Added Content Light Level and Mastering Display Color Volume
> Update table, fix #331

- index.html
Let's get this one in before publishing CR
> Add post-IEND data to security considerations, fix #170

- index.html
and also modified "should" to "may" as per Simon's suggestion
> improved definition for mDCv

- index.html
Status changes, typos, markup and link fixes
> Changes made for Candidate Recommendation

- index.html
Replaces missing descriptions in cICp full range flag
> updated full range flag description

- index.html
> This commit fulfills someone's request to be removed

- index.html
Cleanly add changes  from https://github.com/w3c/PNG-spec/pull/378/commits/9f3747181da170b7bc6a316a1c5e43fd8a361fdd
> mDCv requires cICP

- index.html
- tools.md
1. Updated reference to latest version rather than generic page
> Updated BT.2390 Reference

- index.html
As resolved on 8 Jan 2024 PNG WG phone conference
> Mark eXIf as at-risk, #310

- index.html
- tools.md
Fixed links causing ReSpec issues
> Fixed links causing ReSpec issues

- index.html
This PR fixes the three remaining respec errors.
> Fix respec errors

- index.html
Fixing some of the inconsistencies described in #405.
> Terminology updates

- index.html
This moves cd/m2 from divisor column and moves it to the name column
> moved cd/m2 to name column

- Implementation_Report_3e/index.html
Does not (yet) include libpng 1.6.45 as that is not released yet.
> Implementation Report update, Jan 2025

- index.html
Separate the changes since the CR Draft from the larger list of previous changes
> Split changes

- index.html
URL unchanged, it links to the latest version. Date updated to approval date.
> Update to latest H.273, fix #483

- tools.md
> [Tools] Update for libpng cICP

- index.html
Fixing issue #497, but with a minor rephrasing of the original statement _"[...] seems to be an explicit requirement"_.
> Add eXIf note to the Security Considerations section (#497)

- extensions/Overview.bs
- index.html
As resolved at today's meeting
> Move "Collection" keyword from extensions document to main specification

- index.html
> Removed pointless constraint (unsigned integer can not be negative)

- index.html
Adding changes since the [CR Draft of 25 Jan 2025](https://www.w3.org/TR/2025/CRD-png-3-20250121/)
> [editorial] Update changes list

- Implementation_Report_3e/index.html
New tool, https://github.com/ProgramMax/cicp_inserter
> [ImpRpt] Add cicp_inserter, improve description of pngcheck

- index.html
Small number of fixes for CR Snapshot:
- a couple of link fixes
- boilerplate status updates
> CRS Mar 2025

- tools.md
- official `pngcheck`
- `cicp_inserter`
- a couple of text extractors,
> [tools] Update 

- Implementation_Report_3e/index.html
update link to changes between 2e and 3e to use TR rather than githubio.
add a brief sentence / link to make the source of this report itself more easily discoverable on GitHub
> editorial: index.html use TR changes link, link to report source

- Implementation_Report_3e/README.md
brief README for visitors who may come here by clicking on the GitHub link in the Implementation Report.
feel free to edit prose / links as desired for clarity.
> stub a brief README.md for visitors

- Implementation_Report_3e/index.html
I built Ladybird from scratch (Ununtu running on Win 11 with WSL, Qt toolkit) to run the maunual tests in WPT:
- APNG tests (all pass)
- `iCCP` tests (one fail)
> WPT manual test results for Ladybird
